SECURITYSESSIONID=186a3
USER=aarchtou
MallocNanoZone=0
COMMAND_MODE=unix2003
PATH=/Users/aarchtou/goinfre/.brew/bin:/Users/aarchtou/goinfre/.brew/bin:/Users/aarchtou/goinfre/homebrew/bin:/Users/aarchtou/goinfre/.brew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/goinfre/aarchtou/tools/bin
HOME=/Users/aarchtou
SHELL=/bin/zsh
LaunchInstanceID=6633E247-A092-4D62-870E-F51920B2EE72
__CF_USER_TEXT_ENCODING=0x19030:0x0:0x0
XPC_SERVICE_NAME=0
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.zpo4eAVDBK/Listeners
XPC_FLAGS=0x0
LOGNAME=aarchtou
TMPDIR=/var/folders/zz/zyxvpxvq6csfxvn_n000ch6000341h/T/
ORIGINAL_XDG_CURRENT_DESKTOP=undefined
SHLVL=1
PWD=/Users/aarchtou/Desktop/minishell
ZSH=/Users/aarchtou/.oh-my-zsh
PAGER=less
LESS=-R
LSCOLORS=Gxfxcxdxbxegedabagacad
LS_COLORS=di=1;36:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43
HOMEBREW_NO_AUTO_UPDATE=1
TERM_PROGRAM=vscode
TERM_PROGRAM_VERSION=1.79.1
LANG=en_US.UTF-8
COLORTERM=truecolor
GIT_ASKPASS=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh
VSCODE_GIT_ASKPASS_NODE=/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)
VSCODE_GIT_ASKPASS_EXTRA_ARGS=--ms-enable-electron-run-as-node
VSCODE_GIT_ASKPASS_MAIN=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js
VSCODE_GIT_IPC_HANDLE=/var/folders/zz/zyxvpxvq6csfxvn_n000ch6000341h/T/vscode-git-f912cfcbab.sock
VSCODE_INJECTION=1
ZDOTDIR=/Users/aarchtou
USER_ZDOTDIR=/Users/aarchtou
TERM=xterm-256color
_=/Users/aarchtou/Desktop/minishell/./minishell
